# Generated by Django 4.2.23 on 2025-07-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refactai_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refactorsession',
            name='error_message',
            field=models.TextField(blank=True),
        ),
    ]
