# Generated by Django 4.2.23 on 2025-07-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refactai_app', '0002_refactorsession_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='refactorsession',
            name='add_documentation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='refactorsession',
            name='follow_conventions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refactorsession',
            name='preserve_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='refactorsession',
            name='processing_mode',
            field=models.CharField(choices=[('local', 'Local LLM'), ('api', 'API'), ('hybrid', 'Hybrid')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='refactorsession',
            name='refactor_type',
            field=models.CharField(choices=[('comprehensive', 'Comprehensive'), ('performance', 'Performance'), ('readability', 'Readability'), ('security', 'Security')], default='comprehensive', max_length=20),
        ),
    ]
