# Generated by Django 4.2.23 on 2025-07-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refactai_app', '0003_refactorsession_add_documentation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedfile',
            name='complexity_score',
            field=models.IntegerField(default=0, help_text='Complexity score (0-100)'),
        ),
        migrations.AddField(
            model_name='processedfile',
            name='maintainability_score',
            field=models.IntegerField(default=0, help_text='Maintainability score (0-100)'),
        ),
        migrations.AddField(
            model_name='processedfile',
            name='overall_quality_score',
            field=models.IntegerField(default=0, help_text='Overall quality score (0-100)'),
        ),
        migrations.AddField(
            model_name='processedfile',
            name='readability_score',
            field=models.IntegerField(default=0, help_text='Readability score (0-100)'),
        ),
    ]
